# Generated by Django 5.0.6 on 2024-05-27 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ehr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HAEMATOCRIT', models.FloatField()),
                ('HAEMOGLOBIN', models.FloatField()),
                ('ERYTHROCYTE', models.FloatField()),
                ('LEUCOCYTE', models.FloatField()),
                ('THROMBOCYTE', models.IntegerField()),
                ('MCH', models.FloatField()),
                ('MCHC', models.FloatField()),
                ('MCV', models.FloatField()),
                ('AGE', models.IntegerField()),
                ('SEX', models.IntegerField()),
            ],
        ),
    ]
